{
 "title": "hardware monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "localhost:cpu-*:percent-active:value",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "localhost:cpufreq-*:cpufreq:value",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "localhost:sensors-coretemp-isa-*:temperature-*:value",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Mainboard & GPU temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "localhost:sensors-amdgpu-pci-*:temperature-*:value",
     "type": "timeserie"
    },
    {
     "target": "localhost:sensors-nct6779-isa-*:temperature-*:value",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "target": "localhost:sensors-*:fanspeed-*:value",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "localhost:memory:memory-used:value",
     "type": "timeserie"
    }
   ]
  }
 ]
}